name: dartpad_ui
description: An experimental repo for a web based interactive Dart tutorial

dependencies:
  ace: '>=0.5.10 <0.6.0'
  bootstrap: any
  browser: any
  codemirror: any
  script_inliner: '>=1.0.0 <2.0.0'

dev_dependencies:
  grinder: '>=0.6.0 <0.7.0'
  unittest: any

transformers:
- script_inliner

- $dart2js:
    $exclude: ['web/old/playground1.dart', 'web/old/playground2.dart', 'web/packages/csslib/css.dart']
