name: liftoff
description: An experimental repo for a web based interactive Dart tutorial

dependencies:
  ace: any
  bootstrap: any
  browser: any
  codemirror: any

dev_dependencies:
  unittest: any
