name: dartpad_ui
version: 0.0.1
description: The UI client for a web based interactive Dart service.

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/dartpad_ui
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  ace: '>=0.5.10 <0.6.0'
  browser: any
  codemirror: '>=0.1.0 <0.2.0'
  script_inliner: '>=1.0.0 <2.0.0'

dev_dependencies:
  ghpages_generator: any
  grinder: '>=0.6.0 <0.7.0'
  unittest: any

transformers:
- script_inliner

- $dart2js:
    $exclude: ['web/old/playground1.dart', 'web/old/playground2.dart', 'web/packages/csslib/css.dart']
