name: dartpad_ui
description: An experimental repo for a web based interactive Dart tutorial

dependencies:
  ace: '>=0.5.10 <0.6.0'
  bootstrap: any
  browser: any
  codemirror: any

dev_dependencies:
  unittest: any
